[package]
name = "coolpotos_kern"
version = "0.1.0"
kern = "0.7.6"

[[bin]]
name = "coolpotos_kern"
root = "src/main.rn"

[runtime]
entry = "none"
libc = false
bundle = "base"

[profile.dev]
code-model = "kernel"

[profile.release]
code-model = "kernel"

[build-dependencies]
mkiso = { path = "./mkiso", export = "mkiso" }
mkarchive = { path = "./mkarchive", export = "mkarchive" }

[resources]
limine = { git = "https://github.com/limine-bootloader/Limine.git", tag = "v11.4.0-binary" }
